app = "linebot-ai"
primary_region = "nrt" # 東京區域，對亞洲用戶較快

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[http_service.routes]]
  path = "/"
  handlers = ["http"]

[[http_service.routes]]
  path = "/webhook"
  handlers = ["http"]

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"
  LOG_LEVEL = "INFO"

[mounts]
  source = "linebot_data"
  destination = "/app/data" 