app = "linebot-ai"
primary_region = "nrt" # 東京區域，對亞洲用戶較快

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"

[mounts]
  source = "linebot_data"
  destination = "/app/data" 